language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install . --use-mirrors"
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install coveralls"
# command to run tests
script: nosetests
after_success:
  - coveralls
